import { CommercialLeadItem, CommercialSaleItem, CommercialGoalItem } from '../types/commercial';

// Data dinâmica para garantir que haja dados no dia, na semana e no mês atual
const now = new Date();
const todayISO = now.toISOString();

const getDateDaysAgo = (daysAgo: number): string => {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
};

export const INITIAL_COMMERCIAL_LEADS: CommercialLeadItem[] = [
  // 1. VENDIDOS (Vendas Concretizadas com VGV Realizado)
  {
    id: 'lead-venda-1',
    nome: 'Wesley & Patricia Alves',
    telefone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    email: 'wesley.alves@raxxer.com',
    canalOrigem: 'whatsapp',
    empreendimento: 'Residencial Reserva Imperial',
    renda: 16000,
    cidade: 'São Paulo - SP',
    status: 'vendidos',
    etapa: 'vendidos',
    dataCadastro: getDateDaysAgo(14),
    dataCriacao: getDateDaysAgo(14),
    dataAtualizacao: getDateDaysAgo(1),
    dataAnalise: getDateDaysAgo(10),
    dataAprovacao: getDateDaysAgo(7),
    dataVenda: getDateDaysAgo(1),
    valorAprovado: 380000,
    vgv: 380000,
    vendaContabilizada: true,
    observacoes: 'Contrato assinado. Entrada paga via TED e financiamento Caixa aprovado.',
  },
  {
    id: 'lead-venda-2',
    nome: 'Fernando Henrique Lima',
    telefone: '(11) 97654-3210',
    whatsapp: '(11) 97654-3210',
    email: 'fernando.lima@gmail.com',
    canalOrigem: 'indicacao',
    empreendimento: 'Edifício Horizon Blue',
    renda: 19500,
    cidade: 'Campinas - SP',
    status: 'vendidos',
    etapa: 'vendidos',
    dataCadastro: getDateDaysAgo(22),
    dataCriacao: getDateDaysAgo(22),
    dataAtualizacao: getDateDaysAgo(4),
    dataAnalise: getDateDaysAgo(16),
    dataAprovacao: getDateDaysAgo(11),
    dataVenda: getDateDaysAgo(4),
    valorAprovado: 450000,
    vgv: 450000,
    vendaContabilizada: true,
    observacoes: 'Unidade 84 Torre Sul. Venda concluída e comissão gerada.',
  },
  {
    id: 'lead-venda-3',
    nome: 'Juliana & Marcos Ribeiro',
    telefone: '(19) 99123-8877',
    whatsapp: '(19) 99123-8877',
    email: 'juliana.ribeiro@outlook.com',
    canalOrigem: 'instagram',
    empreendimento: 'Residencial Jardins das Palmeiras',
    renda: 24000,
    cidade: 'Jundiaí - SP',
    status: 'vendidos',
    etapa: 'vendidos',
    dataCadastro: getDateDaysAgo(35),
    dataCriacao: getDateDaysAgo(35),
    dataAtualizacao: getDateDaysAgo(12),
    dataAnalise: getDateDaysAgo(25),
    dataAprovacao: getDateDaysAgo(18),
    dataVenda: getDateDaysAgo(12),
    valorAprovado: 520000,
    vgv: 520000,
    vendaContabilizada: true,
    observacoes: 'Cliente comprou cobertura duplex. Escritura em andamento.',
  },

  // 2. APROVADOS (Crédito Aprovado, aguardando assinatura)
  {
    id: 'lead-aprovado-1',
    nome: 'Lucas Fernandes Macedo',
    telefone: '(11) 98111-2233',
    whatsapp: '(11) 98111-2233',
    email: 'lucas.fernandes@corp.com',
    canalOrigem: 'site',
    empreendimento: 'Residencial Reserva Imperial',
    renda: 12500,
    cidade: 'São Paulo - SP',
    status: 'aprovados',
    etapa: 'aprovados',
    dataCadastro: getDateDaysAgo(8),
    dataCriacao: getDateDaysAgo(8),
    dataAtualizacao: getDateDaysAgo(2),
    dataAnalise: getDateDaysAgo(5),
    dataAprovacao: getDateDaysAgo(2),
    valorAprovado: 310000,
    vgv: 310000,
    observacoes: 'Carta de crédito Santander aprovada. Agendada visita para escolha da unidade.',
  },
  {
    id: 'lead-aprovado-2',
    nome: 'Beatriz Vasconcelos',
    telefone: '(11) 97234-5566',
    whatsapp: '(11) 97234-5566',
    email: 'beatriz.vasc@gmail.com',
    canalOrigem: 'indicacao',
    empreendimento: 'Edifício Horizon Blue',
    renda: 15000,
    cidade: 'Barueri - SP',
    status: 'aprovados',
    etapa: 'aprovados',
    dataCadastro: getDateDaysAgo(12),
    dataCriacao: getDateDaysAgo(12),
    dataAtualizacao: getDateDaysAgo(3),
    dataAnalise: getDateDaysAgo(7),
    dataAprovacao: getDateDaysAgo(3),
    valorAprovado: 360000,
    vgv: 360000,
    observacoes: 'Aprovada com taxa bonificada. Enviada proposta de fechamento.',
  },

  // 3. EM ANÁLISE (Fichas em Análise Bancária/Crédito)
  {
    id: 'lead-analise-1',
    nome: 'Roberto Silveira Neto',
    telefone: '(11) 98345-6789',
    whatsapp: '(11) 98345-6789',
    email: 'roberto.silveira@uol.com.br',
    canalOrigem: 'portal_imobiliario',
    empreendimento: 'Residencial Jardins das Palmeiras',
    renda: 11000,
    cidade: 'São Paulo - SP',
    status: 'em_analise',
    etapa: 'em_analise',
    dataCadastro: getDateDaysAgo(4),
    dataCriacao: getDateDaysAgo(4),
    dataAtualizacao: getDateDaysAgo(1),
    dataAnalise: getDateDaysAgo(1),
    valorAprovado: 290000,
    vgv: 290000,
    observacoes: 'Documentação completa enviada para o correspondente Caixa.',
  },
  {
    id: 'lead-analise-2',
    nome: 'Camila Rocha Andrade',
    telefone: '(19) 98877-6655',
    whatsapp: '(19) 98877-6655',
    email: 'camila.rocha@tech.io',
    canalOrigem: 'instagram',
    empreendimento: 'Reserva Imperial',
    renda: 14200,
    cidade: 'Campinas - SP',
    status: 'em_analise',
    etapa: 'em_analise',
    dataCadastro: getDateDaysAgo(6),
    dataCriacao: getDateDaysAgo(6),
    dataAtualizacao: getDateDaysAgo(2),
    dataAnalise: getDateDaysAgo(2),
    valorAprovado: 340000,
    vgv: 340000,
    observacoes: 'Aguardando comprovante de IRPF para finalizar análise Itaú.',
  },
  {
    id: 'lead-analise-3',
    nome: 'Bruno Castro Martins',
    telefone: '(11) 99456-1122',
    whatsapp: '(11) 99456-1122',
    canalOrigem: 'whatsapp',
    empreendimento: 'Edifício Horizon Blue',
    renda: 9800,
    cidade: 'Osasco - SP',
    status: 'em_analise',
    etapa: 'em_analise',
    dataCadastro: getDateDaysAgo(3),
    dataCriacao: getDateDaysAgo(3),
    dataAtualizacao: todayISO,
    dataAnalise: todayISO,
    valorAprovado: 260000,
    vgv: 260000,
    observacoes: 'Ficha enviada hoje para análise de crédito.',
  },

  // 4. ATENDIMENTOS (Leads em Acompanhamento / Atendimento Ativo)
  {
    id: 'lead-atendimento-1',
    nome: 'Mariana Souza Santos',
    telefone: '(11) 99555-4433',
    whatsapp: '(11) 99555-4433',
    canalOrigem: 'whatsapp',
    empreendimento: 'Residencial Reserva Imperial',
    renda: 13000,
    cidade: 'São Paulo - SP',
    status: 'atendimentos',
    etapa: 'atendimentos',
    dataCadastro: getDateDaysAgo(2),
    dataCriacao: getDateDaysAgo(2),
    dataAtualizacao: todayISO,
    observacoes: 'Muito interessada em 3 dormitórios. Apresentadas plantas no WhatsApp.',
  },
  {
    id: 'lead-atendimento-2',
    nome: 'Thiago Oliveira Costa',
    telefone: '(11) 98777-9900',
    whatsapp: '(11) 98777-9900',
    canalOrigem: 'evento',
    empreendimento: 'Edifício Horizon Blue',
    renda: 18000,
    cidade: 'Santo André - SP',
    status: 'atendimentos',
    etapa: 'atendimentos',
    dataCadastro: getDateDaysAgo(3),
    dataCriacao: getDateDaysAgo(3),
    dataAtualizacao: getDateDaysAgo(1),
    observacoes: 'Esteve no plantão no sábado. Agendando segunda visita com o cônjuge.',
  },
  {
    id: 'lead-atendimento-3',
    nome: 'Carla Mendes Farias',
    telefone: '(11) 97333-2211',
    whatsapp: '(11) 97333-2211',
    canalOrigem: 'instagram',
    empreendimento: 'Residencial Jardins das Palmeiras',
    renda: 10500,
    cidade: 'Guarulhos - SP',
    status: 'atendimentos',
    etapa: 'atendimentos',
    dataCadastro: getDateDaysAgo(5),
    dataCriacao: getDateDaysAgo(5),
    dataAtualizacao: getDateDaysAgo(2),
    observacoes: 'Solicitou simulação de parcelamento de entrada em 36x.',
  },
  {
    id: 'lead-atendimento-4',
    nome: 'Rodrigo Paiva Gomes',
    telefone: '(19) 99888-1144',
    whatsapp: '(19) 99888-1144',
    canalOrigem: 'site',
    empreendimento: 'Reserva Imperial',
    renda: 12000,
    cidade: 'Valinhos - SP',
    status: 'atendimentos',
    etapa: 'atendimentos',
    dataCadastro: todayISO,
    dataCriacao: todayISO,
    dataAtualizacao: todayISO,
    observacoes: 'Novo contato recebido pelo formulário web.',
  },

  // 5. NÃO ATENDERAM
  {
    id: 'lead-nao-atendeu-1',
    nome: 'Diego Ferreira Lima',
    telefone: '(11) 98222-3344',
    whatsapp: '(11) 98222-3344',
    canalOrigem: 'portal_imobiliario',
    empreendimento: 'Edifício Horizon Blue',
    status: 'nao_atenderam',
    etapa: 'nao_atenderam',
    dataCadastro: getDateDaysAgo(6),
    dataCriacao: getDateDaysAgo(6),
    dataAtualizacao: getDateDaysAgo(1),
    observacoes: 'Tentativa de contato por ligação e mensagem. Sem resposta até o momento.',
  },
  {
    id: 'lead-nao-atendeu-2',
    nome: 'Letícia Alencar Dias',
    telefone: '(11) 97111-9988',
    whatsapp: '(11) 97111-9988',
    canalOrigem: 'instagram',
    empreendimento: 'Residencial Jardins das Palmeiras',
    status: 'nao_atenderam',
    etapa: 'nao_atenderam',
    dataCadastro: getDateDaysAgo(4),
    dataCriacao: getDateDaysAgo(4),
    dataAtualizacao: getDateDaysAgo(2),
    observacoes: 'Enviada mensagem no WhatsApp e DM no Instagram. Aguardando retorno.',
  },

  // 6. REPROVADOS
  {
    id: 'lead-reprovado-1',
    nome: 'Vanessa Duarte Pires',
    telefone: '(11) 98666-5544',
    canalOrigem: 'site',
    empreendimento: 'Reserva Imperial',
    renda: 5200,
    status: 'reprovados',
    etapa: 'reprovados',
    dataCadastro: getDateDaysAgo(18),
    dataCriacao: getDateDaysAgo(18),
    dataAtualizacao: getDateDaysAgo(10),
    dataAnalise: getDateDaysAgo(14),
    dataReprovacao: getDateDaysAgo(10),
    motivoDescarteReprovacao: 'Comprometimento de renda elevado e restrições cadastrais no Serasa.',
    observacoes: 'Orientada a regularizar pendências e tentar novamente em 6 meses.',
  },

  // 7. DESCARTADOS
  {
    id: 'lead-descartado-1',
    nome: 'Alexandre Prado Bueno',
    telefone: '(11) 99777-8899',
    canalOrigem: 'outro',
    empreendimento: 'Residencial Jardins das Palmeiras',
    status: 'descartados',
    etapa: 'descartados',
    dataCadastro: getDateDaysAgo(20),
    dataCriacao: getDateDaysAgo(20),
    dataAtualizacao: getDateDaysAgo(15),
    motivoDescarteReprovacao: 'Procurava imóvel apenas para locação, fora do escopo de vendas.',
    observacoes: 'Lead descartado por perfil incompatível.',
  },
];

export const INITIAL_COMMERCIAL_GOALS: CommercialGoalItem[] = [
  {
    id: 'goal-mes-atual',
    titulo: 'Meta Mensal de Vendas & VGV',
    periodo: 'mensal',
    ano: now.getFullYear(),
    mesReferencia: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`,
    metaVendasQuantidade: 10,
    metaVendasValor: 3500000,
    metaLeads: 25,
    metaVisitas: 15,
    metaPropostas: 12,
    realizadoVendasQuantidade: 3,
    realizadoVendasValor: 1350000,
    realizadoLeads: 14,
    realizadoVisitas: 8,
    realizadoPropostas: 6,
    dataCriacao: getDateDaysAgo(30),
    dataAtualizacao: todayISO,
    observacoes: 'Meta de vendas do ciclo atual com acompanhamento semanal.',
  },
];
